name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.17.0
    - name: Get Swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
